Repository cheems-dev/miniproyecto-RPA, pull requests merged in 2023-02, with the labels that each got.

#1 Feat/button component
  package.json
  src/components/banner/banner.tsx
  src/components/global/button.tsx
  src/components/index.ts
  src/components/template/template.tsx
  src/containers/home-container.tsx
  src/containers/template-container.tsx
  src/styles/components/_banner.scss
  src/styles/components/_button.scss
  src/styles/components/banner.scss
  src/styles/elements/_button.scss
  src/styles/index.scss
  src/styles/settings/_colors.scss
  src/styles/utilities/_box-shadow.scss
  src/styles/utilities/_breakpoints.scss
  src/styles/utilities/_media-querys.scss
  yarn.lock
Labels: enhancement

#2 Feat jair/axios
  package.json
  src/api/base.api.ts
  src/api/everything.ts
  src/api/top-headlines.ts
  src/components/banner.tsx
  src/components/template.tsx
  src/containers/home-container.tsx
  src/styles/components/_banner.scss
  src/types/top-new.ts
  yarn.lock
Labels: enhancement

#4 Feat/card components
  src/components/newsCard.tsx
  src/components/newsCardImage.tsx
  src/components/newsCardImageVertical.tsx
  src/styles/components/_newsCard.scss
  src/styles/components/_newsCardImage.scss
  src/styles/components/_newsCardImageVertical.scss
  src/styles/index.scss
Labels: enhancement

#9 feat: add readme
  README.md
Labels: documentation

#10 feat(custom-hook): creacion de un nuevo custom hook para integrar los…
  src/components/search.tsx
  src/config/interceptor.ts
  src/containers/home-container.tsx
  src/hooks/useTopNew.tsx
  src/services/top-headlines.service.ts
Labels: enhancement

#13 fix(validacion para imagen no encontrada): se agrego una imagen y val…
  public/404.png
  src/components/news-card-image-vertical.tsx
  src/components/news-card-image.tsx
  src/components/news-list.tsx
Labels: bug
